### ISSUE TITLE
Score Threshold 自定义选项

### ISSUE THREAD

**Issue by kuyin** [wibus-wee/koishi-plugin-deep-danbooru#5]
### Clear and concise description of the problem

建议增加一个自定义Score Threshold的选项，自己调节返回tag的数量

### Suggested solution

感谢哟

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wibus-wee** [comment]
嗯.. 好提议！但是 #6 里面提到接口出现了问题，可能在修复之前我暂时先不加上这个 feature 了，非常感谢！

**Comment by wibus-wee** [comment]
feature added in release `v1.1.0`
